%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(oc_trace_config_pb).
-define(oc_trace_config_pb, true).

-define(oc_trace_config_pb_gpb_version, "4.4.1").

-ifndef('TRACE_CONFIG_PB_PB_H').
-define('TRACE_CONFIG_PB_PB_H', true).
-record(trace_config_pb,
        {sampler                :: {probability_sampler, oc_trace_config_pb:probability_sampler_pb()} | {constant_sampler, oc_trace_config_pb:constant_sampler_pb()} | {rate_limiting_sampler, oc_trace_config_pb:rate_limiting_sampler_pb()} | undefined, % oneof
         max_number_of_attributes = 0 :: integer() | undefined, % = 4, 32 bits
         max_number_of_annotations = 0 :: integer() | undefined, % = 5, 32 bits
         max_number_of_message_events = 0 :: integer() | undefined, % = 6, 32 bits
         max_number_of_links = 0 :: integer() | undefined % = 7, 32 bits
        }).
-endif.

-ifndef('PROBABILITY_SAMPLER_PB_PB_H').
-define('PROBABILITY_SAMPLER_PB_PB_H', true).
-record(probability_sampler_pb,
        {samplingProbability = 0.0 :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1
        }).
-endif.

-ifndef('CONSTANT_SAMPLER_PB_PB_H').
-define('CONSTANT_SAMPLER_PB_PB_H', true).
-record(constant_sampler_pb,
        {decision = false       :: boolean() | 0 | 1 | undefined % = 1
        }).
-endif.

-ifndef('RATE_LIMITING_SAMPLER_PB_PB_H').
-define('RATE_LIMITING_SAMPLER_PB_PB_H', true).
-record(rate_limiting_sampler_pb,
        {qps = 0                :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
